[package]
name = "pam-ykchallenge"
version = "0.1.0"
authors = ["Raphael Catolino <raphael.catolino@gmail.com>"]
license = "GPLv3"

[dependencies]
pamsm = { git = "https://github.com/rcatolino/pam_sm_rust" }
libc = "^0.2"

[lib]
crate-type = ["dylib"]
